
modLoader="javafml" 
loaderVersion="[36,)"
license="GPL-3.0"
issueTrackerURL="https://github.com/LocusAzzurro/icaruswings_mod/issues"
[[mods]]
modId="locusazzurro_icaruswings"
version="1.16.5-0.1a"
displayName="Icarus Wings"
logoFile="icarus_wings.png"
authors="LocusAzzurro"
credits="Contributors on Github and all who supported development."
description='''A story about bees, feather and the sky. A testament to human ingenuity.'''

[[dependencies.locusazzurro_icaruswings]]
    modId="forge"
    mandatory=true
    versionRange="[36,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.locusazzurro_icaruswings]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5]"
    ordering="NONE"
    side="BOTH"
