
modLoader="javafml" 
loaderVersion="[36,)"
license="GPL-3.0"
issueTrackerURL="https://github.com/LocusAzzurro/icaruswings_mod/issues"
[[mods]]
modId="locusazzurro_icaruswings"
version="${version}"
displayName="${mod_name}"
logoFile="${mod_icon}"
authors="${mod_author}"
credits="${mod_credits}"
description='''${mod_description}'''

[[dependencies.locusazzurro_icaruswings]]
    modId="forge"
    mandatory=true
    versionRange="[36,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.locusazzurro_icaruswings]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5]"
    ordering="NONE"
    side="BOTH"
