
modLoader="javafml"
loaderVersion="${loader_version_range}"
license="GPL-3.0"
issueTrackerURL="https://github.com/LocusAzzurro/icaruswings_mod/issues"

[[mods]]
modId="locusazzurro_icaruswings"
version="${mod_version}"
displayName="${mod_name}"
logoFile="${mod_icon}"
authors="${mod_authors}"
credits="${mod_credits}"
description='''${mod_description}'''


[[dependencies.${mod_id}]]
modId="neoforge"
type="required"
versionRange="${neoforge_version_range}"
ordering="NONE"
side="BOTH"
[[dependencies.${mod_id}]]
modId="minecraft"
type="required"
versionRange="${minecraft_version_range}"
ordering="NONE"
side="BOTH"
