@MethodsReturnNonnullByDefault
@ParametersAreNonnullByDefault
package org.mineplugin.locusazzurro.icaruswings.client.particle;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;