@MethodsReturnNonnullByDefault
@ParametersAreNonnullByDefault
package org.mineplugin.locusazzurro.icaruswings.common.item.transportcard;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;