@MethodsReturnNonnullByDefault
@ParametersAreNonnullByDefault
package org.mineplugin.locusazzurro.icaruswings.common.loot;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;