@MethodsReturnNonnullByDefault
@ParametersAreNonnullByDefault
package org.mineplugin.locusazzurro.icaruswings.common.block;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;